/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#ifndef WatDHT_CONSTANTS_H
#define WatDHT_CONSTANTS_H

#include "WatDHT_types.h"

namespace WatDHT {

class WatDHTConstants {
 public:
  WatDHTConstants();

};

extern const WatDHTConstants g_WatDHT_constants;

} // namespace

#endif
