/**
 * Autogenerated by Thrift Compiler (0.7.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
#include "WatDHT_constants.h"

namespace WatDHT {

const WatDHTConstants g_WatDHT_constants;

WatDHTConstants::WatDHTConstants() {
}

} // namespace

